#!/bin/sh

cd ~

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export WLR_NO_HARDWARE_CURSORS=1

export SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1
export GTK_THEME=Catppuccin-blue:dark
exec Hyprland
