#!/bin/sh

current_workspace=$(hyprctl activeworkspace | grep 'workspace ID' | head -n1 | awk '{print $3}')
hyprctl dispatch movetoworkspacesilent $1
sleep 1
~/.config/hypr/scripts/smart-tile/tile-active-workspace $current_workspace
~/.config/hypr/scripts/smart-tile/tile-active-workspace $1
