#!/bin/sh

current_workspace=$(hyprctl activeworkspace | grep 'workspace ID' | head -n1 | awk '{print $3}')
rm "$(dirname "$0")"/tmp/canvas-pos-$current_workspace
python ~/.config/hypr/scripts/smart-tile.py
