
[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.8
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[general]
live_config_reload = true
import = ["/home/xun/.config/alacritty/tokyo-night.toml"]

[terminal]
